development:
  cloud_name: dm1hql92i
  api_key: '127232945891332'
  api_secret: M3QJW0l_p3kc0gtqkpFS-4-1INY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dm1hql92i
  api_key: '127232945891332'
  api_secret: M3QJW0l_p3kc0gtqkpFS-4-1INY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dm1hql92i
  api_key: '127232945891332'
  api_secret: M3QJW0l_p3kc0gtqkpFS-4-1INY
  enhance_image_tag: true
  static_image_support: false
